services:
  # Django Backend
  - type: web
    name: location-tracker-django
    env: python
    rootDir: realtime-tracker
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn django_api.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_api.production_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "location-tracker-4zk7.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://location-tracker-135y.vercel.app"

  # Node.js Socket Server
    - type: web
      name: location-tracker-node
      env: node
      rootDir: realtime-tracker/server
      buildCommand: "npm install"
      startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DJANGO_API_BASE
        value: "https://location-tracker-4zk7.onrender.com/api"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://location-tracker-135y.vercel.app"