# Generated by Django 4.2.7 on 2025-08-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tracking_and_coordination'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movement',
            new_name='api_movemen_room_id_25a915_idx',
            old_name='api_movemen_room_id_6a6a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='movement',
            new_name='api_movemen_user_id_c91631_idx',
            old_name='api_movemen_user_id_8a0bd4_idx',
        ),
    ]
