# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_movemen_room_id_6a6a2a_idx_api_movemen_room_id_25a915_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]